dist: bionic
language: shell
os: linux

services:
  - docker

env:
  jobs:
  - COQ_VERSION="dev"

install: |
  docker run -d -i --init --name=COQ -v ${TRAVIS_BUILD_DIR}:/home/coq/demo -w /home/coq/demo coqorg/coq:${COQ_VERSION}
  docker exec COQ /bin/bash --login -c "
    echo \"Build triggered by ${TRAVIS_EVENT_TYPE}\"
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
    set -ex
    opam config list
    opam repo list
    opam list
    "
before_script:
- |
  docker exec COQ /bin/bash --login -c "
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
    sudo chown -R coq:coq /home/coq/demo
    "
script:
- echo -e "${ANSI_YELLOW}Building ${TRAVIS_REPO_SLUG}...${ANSI_RESET}" && echo -en 'travis_fold:start:build\\r'
- docker exec COQ /bin/bash --login -c "make -j2 -k"
- echo -en 'travis_fold:end:build\\r'

after_script:
- docker stop COQ
